### ISSUE TITLE
Fix command line input

### ISSUE THREAD

**Issue by RimorRes** [Oxyde2/Preflight#1]
Remove shell and use arg parser to take in commands from a terminal call.

**Comment by Naapi** [comment]
What command(s) it would require to take? Also, what you mean by remove shell?

**Comment by RimorRes** [comment]
The following inputs should be parsed:
- find maximum burn time **or** burn time (required)
- graphing ( optional )
- output file (optional)
- input file ( required )
- landing/suicide burn ( optional )

**Comment by RimorRes** [comment]
This issue is no longer relevant as Preflight has become a [PyPi package](https://pypi.org/project/preflightpy/). 📦
Furthermore, GUI development will be moved to Preflight-GUI in the near future. 🎨
