### ISSUE TITLE
System.py mock tests

### ISSUE THREAD

**Issue by RimorRes** [Oxyde2/Preflight#3]
Add more tests using **pytest** for better coverage. After installing the `pytest-cov`, `coverage` and `pytest` modules through PIP, you can check coverage by running `pytest -v --cov=preflight` at the root of the project or by running `coverage report`.

**Comment by Oxyde2** [comment]
@nowtryz

**Comment by rvmoura96** [comment]
May I help on this one?

**Comment by RimorRes** [comment]
This issue is still open

**Comment by RimorRes** [comment]
Only tests left to write up concern `system.py`
Not looking forward to this 😢
